INSERT INTO
    PROPERTIES (
        APPLICATION,
        PROFILE,
        LABEL,
        KEY,
        VALUE
    )
VALUES (
        'property-precedence',
        'dev',
        '1.1',
        'prop1',
        'val11'
    ),
    (
        'property-precedence',
        'dev',
        '1.1',
        'prop2',
        'val12'
    ),
    (
        'property-precedence',
        'dev',
        '1.1',
        'prop3',
        'val13'
    ),
    (
        'property-precedence',
        'dev',
        '1.0',
        'prop1',
        'val21'
    ),
    (
        'property-precedence',
        'dev',
        '1.0',
        'prop2',
        'val22'
    ),
    (
        'property-precedence',
        'dev',
        '1.0',
        'prop3',
        'val23'
    );